name: MultiTP (EDITED)
main: legoboy\multitp\MultiTP
version: 2.0.1
api: 1.11.0
description: MultiTP teleport a player in a random position in the world.
author: Legoboy

commands:
 mtpset:
  description: Set a random spawn position at current player position.
  usage: "Usage: /mtpset"
  permission: multitp.command.opcommands
 mtpreset:
  description: Reset all random spawn positions.
  usage: "Usage: /mtpreset"
  permission: multitp.command.opcommands
 mtpinfo:
  description: More informations about MultiTP.
  usage: "Usage: /mtpinfo"

permissions:
 multitp.command.opcommands:
  description: "MultiTP OP permissions"
  default: op
